name: vHive build tests

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  workflow_dispatch:

env:
  GOOS: linux
  GO111MODULE: on

jobs:

  build:
    strategy:
      matrix:
        go: ['1.18', '1.19']
      # Build all variants regardless of failures
      fail-fast: false

    name: Build and check code quality
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        # to add commit DCO checks later
        fetch-depth: 21

    - name: Check code
      uses: golangci/golangci-lint-action@v3.6.0
      with:
        args: --timeout 5m

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -race -v -a ./...
