name: vHive CRI tests

on:
  workflow_call:
    inputs:
      sandbox:
        required: true
        type: string

env:
  GO111MODULE: on

jobs:
  cri-tests:
    name: CRI tests
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}
      GITHUB_VHIVE_ARGS: "-dbg"
    # runs-on: ${{ fromJSON(format('["self-hosted", "{0}-cri"]', inputs.sandbox)) }}
    runs-on: ubuntu-20.04

    steps:

      - name: Host Info
        run: |
          echo $HOSTNAME
          echo $GITHUB_RUN_ID

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Build setup scripts
        run: pushd scripts && go build -o vhive_setup && popd

      - name: Setup vHive CRI test environment
        run: ./scripts/github_runner/setup_cri_test_env.sh ${{ inputs.sandbox }}

      - name: Run vHive CRI tests
        run: source /etc/profile && go clean -testcache && go test ./cri -v -race -cover

      - name: Archive log artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: ctrd-logs
          path: |
            /tmp/ctrd-logs/${{ github.run_id }}

      - name: Cleaning
        if: ${{ always() }}
        run: ./scripts/github_runner/clean_cri_runner.sh ${{ inputs.sandbox }}
