name: vHive stock-only mode CRI tests

on:
    push:
      branches: [ main ]
      paths-ignore:
      - 'docs/**'
      - '**.md'
    pull_request:
      branches: [ main ]
      paths-ignore:
      - 'docs/**'
      - '**.md'
    workflow_dispatch:
  
env:
    GOOS: linux
    GO111MODULE: on

jobs:
    stock_setup_test:
        name: Stock-only mode setup test
        runs-on: ubuntu-20.04
        steps:
        - name: Set up Go 1.19
          uses: actions/setup-go@v4
          with:
            go-version: '1.19'
        
        - name: Check out the code
          uses: actions/checkout@v3

        - name: Build scripts
          run: pushd scripts && go build -o setup_tool && popd

        - name: Set up Node
          run: ./scripts/setup_tool setup_node stock-only use-stargz

        - name: Start Containerd
          run: sudo containerd &

        - name: Build vHive host orchestrator
          run: source /etc/profile && go build
        
        - name: Run the single node cluster setup script
          run: ./scripts/setup_tool create_one_node_cluster stock-only && sleep 2m

        - name: Deploy zipkin
          run: ./scripts/setup_tool setup_zipkin && sleep 1m

        - name: Create helloworld container
          run: kn service create helloworld-go --image gcr.io/knative-samples/helloworld-go --env TARGET="vHive CRI test"

        - name: Invoke the deployed function
          run: curl http://helloworld-go.default.192.168.1.240.sslip.io

        - name: Archive log artifacts
          if: ${{ always() }}
          uses: actions/upload-artifact@v3
          with:
            name: ctrd-logs
            path: |
              ${{ github.workspace }}/*.log